version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=stadiondb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root1234
    depends_on:
      - db
    volumes:
      - web-data:/path/to/web/data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: stadiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root1234

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  web-data:
  db-data:
